version: "3.9"

services:
  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app:Z
      - node_modules_nestjs:/usr/src/app/node_modules
    env_file:
      - ".env"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    command: npm run start:dev

  db:
    container_name: postgres-db
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - postgres_data_nestjs:/var/lib/postgresql/data:Z

volumes:
  postgres_data_nestjs:
  node_modules_nestjs:
